version: '3'

services:
  app:
    restart: always
    build: .
    container_name: spotseeker-server
    volumes:
      - ./spotseeker_server:/app/spotseeker_server
    ports:
      - "${PORT:-8000}:8000"
    environment:
      ENV: localdev
      AUTH_MODULE: ${AUTH_MODULE:-all_ok}
      SPOTSEEKER_AUTH_ADMINS: ${SPOTSEEKER_AUTH_ADMINS}
      SPOTSEEKER_WEB_SERVER_HOST: ${SPOTSEEKER_WEB_SERVER_HOST}
      SPOTSEEKER_WEB_OAUTH_KEY: ${SPOTSEEKER_WEB_OAUTH_KEY}
      SPOTSEEKER_WEB_OAUTH_SECRET: ${SPOTSEEKER_WEB_OAUTH_SECRET}
      SPOTSEEKER_WEB_OAUTH_USER: ${SPOTSEEKER_WEB_OAUTH_USER}
      SPOTSEEKER_SYNC_TECHLOAN_COUNT: ${SPOTSEEKER_SYNC_TECHLOAN_COUNT}
    stdin_open: true
    tty: true