version: '3'

services:
  app:
    restart: always
    build: .
    container_name: spotseeker-server
    volumes:
      - ./spotseeker_server:/app/spotseeker_server
    ports:
      - "${PORT:-8000}:8000"
    environment:
      ENV: localdev
      PORT: 8000
      AUTH_MODULE: all_ok
    stdin_open: true
    tty: true