version: '3'

services:
  app:
    restart: always
    build: .
    container_name: spotseeker-server
    volumes:
      - ./spotseeker_server:/app/spotseeker_server
    ports:
      - "${PORT:-8000}:8000"
    environment:
      ENV: localdev
      SPOTSEEKER_OAUTH_ENABLED: ${SPOTSEEKER_OAUTH_ENABLED}
      SPOTSEEKER_AUTH_ADMINS: ${SPOTSEEKER_AUTH_ADMINS}
    stdin_open: true
    tty: true