autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
targetAverageUtilization: 100
resources:
  requests:
    cpu: 90m
ingress:
  enabled: true
  tls:
    spotseeker:
      secretName: api.scout.uw.edu-ingress-cert
      hosts:
        - api.scout.uw.edu
  hosts:
    spotseeker:
      host: api.scout.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "500"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: spotseeker-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.196
  servicePort: 3306
database:
  engine: mysql
  name: api
  hostname: spotseeker-db-service
  secretName: api.scout.uw.edu-sql-secrets
repo: spotseeker
instance: prod
image:
  repository: gcr.io/uwit-mci-axdd/spotseeker
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
gcsCredentials:
  mounted: true
  secretName: api.scout.uw.edu-gc-service-credentials
cronjob:
  enabled: false
environmentVariables:
  - name: AUTH_MODULE
    value: oauth
  - name: CLUSTER_CNAME
    value: api.scout.uw.edu
  - name: ENV
    value: prod
  - name: WEBSERVER
    value: nginx
  - name: CACHE_MAX_ENTRIES
    value: "1000"
  - name: CACHE_TIMEOUT
    value: "86400"
externalSecrets:
  enabled: true
  secrets:
    - name: api.scout.uw.edu-secrets
      externalKey: axdd/kv/data/scout/prod-api/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: spotseeker-auth-admins
          property: spotseeker-auth-admins
        - name: storage-bucket-name
          property: storage-bucket-name
        - name: storage-project-id
          property: storage-project-id
        - name: spotseeker-techloan-url
          property: spotseeker-techloan-url
        - name: spotseeker-web-server-host
          property: spotseeker-web-server-host
        - name: spotseeker-web-oauth-key
          property: spotseeker-web-oauth-key
        - name: spotseeker-web-oauth-secret
          property: spotseeker-web-oauth-secret
        - name: spotseeker-web-oauth-user
          property: spotseeker-web-oauth-user
    - name: api.scout.uw.edu-sql-secrets
      externalKey: axdd/kv/data/scout/common/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: api.scout.uw.edu-gc-service-credentials
      externalKey: axdd/kv/data/scout/common/gc-service-credentials
      data:
        - name: credentials.json
          property: credentials.json
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: api.scout.uw.edu-secrets
    secretKey: django-secret
  spotseekerAuthAdmins:
    name: SPOTSEEKER_AUTH_ADMINS
    secretName: api.scout.uw.edu-secrets
    secretKey: spotseeker-auth-admins
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: api.scout.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: api.scout.uw.edu-secrets
    secretKey: storage-project-id
  spotseekerTechloanUrl:
    name: SPOTSEEKER_TECHLOAN_URL
    secretName: api.scout.uw.edu-secrets
    secretKey: spotseeker-techloan-url
  spotseekerWebServerHost:
    name: SPOTSEEKER_WEB_SERVER_HOST
    secretName: api.scout.uw.edu-secrets
    secretKey: spotseeker-web-server-host
  spotseekerWebOauthKey:
    name: SPOTSEEKER_WEB_OAUTH_KEY
    secretName: api.scout.uw.edu-secrets
    secretKey: spotseeker-web-oauth-key
  spotseekerWebOauthSecret:
    name: SPOTSEEKER_WEB_OAUTH_SECRET
    secretName: api.scout.uw.edu-secrets
    secretKey: spotseeker-web-oauth-secret
  spotseekerWebOauthUser:
    name: SPOTSEEKER_WEB_OAUTH_USER
    secretName: api.scout.uw.edu-secrets
    secretKey: spotseeker-web-oauth-user
