autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
targetAverageUtilization: 100
resources:
  limits:
    cpu: 1.0
    memory: 1280Mi
  requests:
    cpu: 256m
    memory: 1024Mi
ingress:
  enabled: true
  tls:
    spotseeker:
      secretName: prod.spotseeker.uw.edu-ingress-cert
      hosts:
        - prod.spotseeker.uw.edu
  hosts:
    spotseeker:
      host: prod.spotseeker.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: spotseeker-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.37  # CHANGE TO MATCH
  servicePort: 3306
database:
  engine: mysql
  name: spotseeker_prod
  hostname: spotseeker-db-service
  secretName: prod.spotseeker.uw.edu-sql-secrets
repo: spotseeker
instance: prod
image:
  repository: gcr.io/uwit-mci-axdd/spotseeker
  tag: IMAGE_TAG
memcached:
  enabled: false
cronjob:
  enabled: false
certs:
  mounted: true
  certPath: /certs/prod.spotseeker.uw.edu-uwca.cert
  keyPath: /certs/prod.spotseeker.uw.edu-uwca.key
  secretName: prod.spotseeker.uw.edu-uwca-certs
environmentVariables:
  - name: AUTH_MODULE
    value: oauth
  - name: CLUSTER_CNAME
    value: prod.spotseeker.uw.edu
  - name: ENV
    value: prod
  - name: WEBSERVER
    value: nginx
externalSecrets:
  enabled: true
  secrets:
    - name: prod.spotseeker.uw.edu-secrets
      externalKey: axdd/kv/data/spotseeker/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: spotseeker-auth-admins
          property: spotseeker-auth-admins
    - name: prod.spotseeker.uw.edu-sql-secrets
      externalKey: axdd/kv/data/spotseeker/prod/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: prod.spotseeker.uw.edu-uwca-certs
      externalKey: axdd/kv/data/spotseeker/prod/uwca-certs
      data:
        - name: prod.spotseeker.uw.edu-uwca.cert
          property: prod.spotseeker.uw.edu-uwca.cert
        - name: prod.spotseeker.uw.edu-uwca.key
          property: prod.spotseeker.uw.edu-uwca.key
    - name: prod.spotseeker.uw.edu-ic-cert
      externalKey: axdd/kv/data/spotseeker/prod/ic-certs
      data:
        - name: prod.spotseeker.uw.edu-ic.cert
          property: prod.spotseeker.uw.edu-ic.cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: prod.spotseeker.uw.edu-secrets
    secretKey: django-secret
  spotseekerAuthAdmins:
    name: SPOTSEEKER_AUTH_ADMINS
    secretName: prod.spotseeker.uw.edu-secrets
    secretKey: spotseeker-auth-admins
