ingress:
  enabled: true
  tls:
    spotseeker:
      secretName: test.spotseeker.uw.edu-ingress-cert
      hosts:
        - test.spotseeker.uw.edu
  hosts:
    spotseeker:
      host: test.spotseeker.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
    nginx.ingress.kubernetes.io/permanent-redirect: https://test.spotseeker.uw.edu
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true
externalService:
  enabled: true
  name: spotseeker-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.37   # CHANGE TO MATCH
  servicePort: 3306
database:
  engine: mysql
  name: spotseeker_test
  hostname: spotseeker-db-service
  secretName: test.spotseeker.uw.edu-sql-secrets
repo: spotseeker
instance: test
image:
  repository: gcr.io/uwit-mci-axdd/spotseeker
  tag: IMAGE_TAG
memcached:
  enabled: false
gcsCredentials:
  mounted: true
  secretName: test.spotseeker.uw.edu-gc-service-credentials
cronjob:
  enabled: false
certs:
  mounted: true
  certPath: /certs/test.spotseeker.uw.edu-uwca.cert
  keyPath: /certs/test.spotseeker.uw.edu-uwca.key
  secretName: test.spotseeker.uw.edu-uwca-certs
environmentVariables:
  - name: AUTH_MODULE
    value: oauth
  - name: CLUSTER_CNAME
    value: test.spotseeker.uw.edu
  - name: ENV
    value: test
  - name: WEBSERVER
    value: nginx
externalSecrets:
  enabled: true
  secrets:
    - name: test.spotseeker.uw.edu-secrets
      externalKey: axdd/kv/data/spotseeker/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: spotseeker-auth-admins
          property: spotseeker-auth-admins
        - name: storage-bucket-name
          property: storage-bucket-name
        - name: storage-project-id
          property: storage-project-id
    - name: test.spotseeker.uw.edu-sql-secrets
      externalKey: axdd/kv/data/spotseeker/test/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test.spotseeker.uw.edu-uwca-certs
      externalKey: axdd/kv/data/spotseeker/test/uwca-certs
      data:
        - name: test.spotseeker.uw.edu-uwca.cert
          property: test.spotseeker.uw.edu-uwca.cert
        - name: test.spotseeker.uw.edu-uwca.key
          property: test.spotseeker.uw.edu-uwca.key
    - name: test.spotseeker.uw.edu-ic-certs
      externalKey: axdd/kv/data/spotseeker/test/ic-certs
      data:
        - name: test.spotseeker.uw.edu-ic.cert
          property: test.spotseeker.uw.edu-ic.cert
    - name: test.spotseeker.uw.edu-gc-service-credentials
      externalKey: axdd/kv/data/spotseeker/test/gc-service-credentials
      data:
        - name: credentials.json
          property: credentials.json
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.spotseeker.uw.edu-secrets
    secretKey: django-secret
  spotseekerAuthAdmins:
    name: SPOTSEEKER_AUTH_ADMINS
    secretName: test.spotseeker.uw.edu-secrets
    secretKey: spotseeker-auth-admins
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: test.spotseeker.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: test.spotseeker.uw.edu-secrets
    secretKey: storage-project-id
