# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-07 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotseeker_server', '0004_auto_20200702_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritespot',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='favoritespot',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sharedspace',
            name='space',
        ),
        migrations.RemoveField(
            model_name='sharedspacerecipient',
            name='shared_space',
        ),
        migrations.RemoveField(
            model_name='spacereview',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='spacereview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='spacereview',
            name='space',
        ),
        migrations.DeleteModel(
            name='FavoriteSpot',
        ),
        migrations.DeleteModel(
            name='SharedSpace',
        ),
        migrations.DeleteModel(
            name='SharedSpaceRecipient',
        ),
        migrations.DeleteModel(
            name='SpaceReview',
        ),
    ]
