# Generated by Django 2.2.28 on 2023-04-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotseeker_server', '0005_auto_20230406_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='client_credential',
            field=models.CharField(blank=True, max_length=255),
        ),

        migrations.AlterField(
            model_name='itemextendedinfo',
            name='item',
            field=models.ForeignKey(blank=True, to='spotseeker_server.Item', null=True, on_delete=models.CASCADE),
        ),

        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(to='spotseeker_server.Item', on_delete=models.CASCADE),
        ),

        migrations.AlterField(
            model_name='spotavailablehours',
            name='spot',
            field=models.ForeignKey(to='spotseeker_server.Spot', on_delete=models.CASCADE),
        ),

        migrations.AlterField(
            model_name='spotextendedinfo',
            name='spot',
            field=models.ForeignKey(to='spotseeker_server.Spot', on_delete=models.CASCADE),
        ),

        migrations.AlterField(
            model_name='spotimage',
            name='spot',
            field=models.ForeignKey(to='spotseeker_server.Spot', on_delete=models.CASCADE),
        ),

        migrations.AlterField(
            model_name='item',
            name='spot',
            field=models.ForeignKey(blank=True, to='spotseeker_server.Spot', null=True, on_delete=models.CASCADE),
        ),
    ]
