# Generated by Django 2.2.28 on 2023-06-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotseeker_server', '0007_remove_client_access_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrustedOAuthClient',
        ),
    ]
