# Generated by Django 2.2.28 on 2023-05-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotseeker_server', '0006_auto_20230420_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='access_token',
        ),
    ]
